
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action newAction;
	private global::Gtk.Action preferencesAction;
	private global::Gtk.Action bfghdgdfgdfAction;
	private global::Gtk.Action gdfgdfgdfgAction;
	private global::Gtk.Action gdfgdfgdfAction;
	private global::Gtk.Action infoAction;
	private global::Gtk.Action directoryAction;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.ComboBox combobox1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeview1;
	private global::Gtk.VButtonBox vbuttonbox1;
	private global::Gtk.Button button22;
	private global::Gtk.Button button23;
	private global::Gtk.Button emailButton;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("Nuevo registro"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Nuevo registro");
		w1.Add (this.newAction, null);
		this.preferencesAction = new global::Gtk.Action ("preferencesAction", global::Mono.Unix.Catalog.GetString ("Preferencias"), null, "gtk-preferences");
		this.preferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferencias");
		w1.Add (this.preferencesAction, null);
		this.bfghdgdfgdfAction = new global::Gtk.Action ("bfghdgdfgdfAction", global::Mono.Unix.Catalog.GetString ("bfghdgdfgdf"), null, null);
		this.bfghdgdfgdfAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("bfghdgdfgdf");
		w1.Add (this.bfghdgdfgdfAction, null);
		this.gdfgdfgdfgAction = new global::Gtk.Action ("gdfgdfgdfgAction", global::Mono.Unix.Catalog.GetString ("gdfgdfgdfg"), null, null);
		this.gdfgdfgdfgAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("gdfgdfgdfg");
		w1.Add (this.gdfgdfgdfgAction, null);
		this.gdfgdfgdfAction = new global::Gtk.Action ("gdfgdfgdfAction", global::Mono.Unix.Catalog.GetString ("gdfgdfgdf"), null, null);
		this.gdfgdfgdfAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("gdfgdfgdf");
		w1.Add (this.gdfgdfgdfAction, null);
		this.infoAction = new global::Gtk.Action ("infoAction", global::Mono.Unix.Catalog.GetString ("Acerca de..."), null, "gtk-info");
		this.infoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Acerca de...");
		w1.Add (this.infoAction, null);
		this.directoryAction = new global::Gtk.Action ("directoryAction", global::Mono.Unix.Catalog.GetString ("Nueva categoría"), null, "gtk-directory");
		this.directoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Nueva categoría");
		w1.Add (this.directoryAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Secretaría Electrial");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SecretariaDataBase.logo-ico");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='directoryAction' action='directoryAction'/><toolitem name='preferencesAction' action='preferencesAction'/><toolitem name='infoAction' action='infoAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
		this.vbox3.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.toolbar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(6));
		// Container child vbox1.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.Name = "combobox1";
		this.vbox1.Add (this.combobox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.combobox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView ();
		this.treeview1.WidthRequest = 500;
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.treeview1.SearchColumn = 0;
		this.GtkScrolledWindow.Add (this.treeview1);
		this.hbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
		w5.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button22 = new global::Gtk.Button ();
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseStock = true;
		this.button22.UseUnderline = true;
		this.button22.Label = "gtk-delete";
		this.vbuttonbox1.Add (this.button22);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button22]));
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button23 = new global::Gtk.Button ();
		this.button23.CanFocus = true;
		this.button23.Name = "button23";
		this.button23.UseStock = true;
		this.button23.UseUnderline = true;
		this.button23.Label = "gtk-open";
		this.vbuttonbox1.Add (this.button23);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button23]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.emailButton = new global::Gtk.Button ();
		this.emailButton.CanFocus = true;
		this.emailButton.Name = "emailButton";
		// Container child emailButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w8 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w9 = new global::Gtk.HBox ();
		w9.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w10 = new global::Gtk.Image ();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_mail-send", global::Gtk.IconSize.Button);
		w9.Add (w10);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w12 = new global::Gtk.Label ();
		w12.LabelProp = global::Mono.Unix.Catalog.GetString ("Send by email");
		w9.Add (w12);
		w8.Add (w9);
		this.emailButton.Add (w8);
		this.vbuttonbox1.Add (this.emailButton);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.emailButton]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox2.Add (this.vbuttonbox1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbuttonbox1]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w18.Position = 1;
		this.vbox3.Add (this.vbox1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox1]));
		w19.PackType = ((global::Gtk.PackType)(1));
		w19.Position = 1;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 701;
		this.DefaultHeight = 432;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.preferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
		this.infoAction.Activated += new global::System.EventHandler (this.OnInfoActionActivated);
		this.directoryAction.Activated += new global::System.EventHandler (this.OnDirectoryActionActivated);
		this.combobox1.Changed += new global::System.EventHandler (this.OnCombobox1Changed);
		this.button22.Clicked += new global::System.EventHandler (this.OnButton22Clicked);
		this.button23.Clicked += new global::System.EventHandler (this.OnButton23Clicked);
		this.emailButton.Clicked += new global::System.EventHandler (this.OnEmailButtonClicked);
	}
}
