
// This file has been generated by the GUI designer. Do not modify.
namespace SecretariaDataBase
{
	public partial class NewBox
	{
		private global::Gtk.Table table1;
		private global::Gtk.Label directionLabel;
		private global::Gtk.HBox hbox1;
		private global::Gtk.RadioButton inRadiobutton;
		private global::Gtk.RadioButton outRadiobutton;
		private global::Gtk.Entry idEntry;
		private global::Gtk.Label IdLabel;
		private global::Gtk.Entry nameEntry;
		private global::Gtk.Label nameLabel;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SecretariaDataBase.NewBox
			this.Name = "SecretariaDataBase.NewBox";
			this.Title = global::Mono.Unix.Catalog.GetString ("Nueva categoría");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SecretariaDataBase.logo-ico");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			// Internal child SecretariaDataBase.NewBox.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.directionLabel = new global::Gtk.Label ();
			this.directionLabel.Name = "directionLabel";
			this.directionLabel.Xalign = 0F;
			this.directionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Tipo:");
			this.table1.Add (this.directionLabel);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.directionLabel]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.inRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Entrada"));
			this.inRadiobutton.CanFocus = true;
			this.inRadiobutton.Name = "inRadiobutton";
			this.inRadiobutton.Active = true;
			this.inRadiobutton.DrawIndicator = true;
			this.inRadiobutton.UseUnderline = true;
			this.inRadiobutton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox1.Add (this.inRadiobutton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.inRadiobutton]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.outRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Salida"));
			this.outRadiobutton.CanFocus = true;
			this.outRadiobutton.Name = "outRadiobutton";
			this.outRadiobutton.DrawIndicator = true;
			this.outRadiobutton.UseUnderline = true;
			this.outRadiobutton.Group = this.inRadiobutton.Group;
			this.hbox1.Add (this.outRadiobutton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.outRadiobutton]));
			w4.Position = 1;
			this.table1.Add (this.hbox1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox1]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.idEntry = new global::Gtk.Entry ();
			this.idEntry.CanFocus = true;
			this.idEntry.Name = "idEntry";
			this.idEntry.IsEditable = true;
			this.idEntry.InvisibleChar = '•';
			this.table1.Add (this.idEntry);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.idEntry]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.IdLabel = new global::Gtk.Label ();
			this.IdLabel.Name = "IdLabel";
			this.IdLabel.Xalign = 0F;
			this.IdLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Id:");
			this.table1.Add (this.IdLabel);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.IdLabel]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nameEntry = new global::Gtk.Entry ();
			this.nameEntry.CanFocus = true;
			this.nameEntry.Name = "nameEntry";
			this.nameEntry.IsEditable = true;
			this.nameEntry.InvisibleChar = '•';
			this.table1.Add (this.nameEntry);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.nameEntry]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nameLabel = new global::Gtk.Label ();
			this.nameLabel.Name = "nameLabel";
			this.nameLabel.Xalign = 0F;
			this.nameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.table1.Add (this.nameLabel);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.nameLabel]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.table1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Internal child SecretariaDataBase.NewBox.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonCancel]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonOk]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 316;
			this.DefaultHeight = 147;
			this.Show ();
			this.inRadiobutton.Toggled += new global::System.EventHandler (this.OnInRadiobuttonToggled);
			this.outRadiobutton.Toggled += new global::System.EventHandler (this.OnOutRadiobuttonToggled);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
