
// This file has been generated by the GUI designer. Do not modify.
namespace SecretariaElectrial
{
	public partial class Preferences
	{
		private global::Gtk.Frame pathFrame;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.FileChooserButton pathFileChooserButton;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.CheckButton readonlyCheckbutton;
		private global::Gtk.Label GtkLabel4;
		private global::Gtk.Button buttonClose;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SecretariaElectrial.Preferences
			this.Name = "SecretariaElectrial.Preferences";
			this.Title = global::Mono.Unix.Catalog.GetString ("Preferences");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			// Internal child SecretariaElectrial.Preferences.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.pathFrame = new global::Gtk.Frame ();
			this.pathFrame.Name = "pathFrame";
			this.pathFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child pathFrame.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.pathFileChooserButton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select folder"), ((global::Gtk.FileChooserAction)(2)));
			this.pathFileChooserButton.Name = "pathFileChooserButton";
			this.GtkAlignment2.Add (this.pathFileChooserButton);
			this.pathFrame.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Path</b>");
			this.GtkLabel2.UseMarkup = true;
			this.pathFrame.LabelWidget = this.GtkLabel2;
			w1.Add (this.pathFrame);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.pathFrame]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.readonlyCheckbutton = new global::Gtk.CheckButton ();
			this.readonlyCheckbutton.CanFocus = true;
			this.readonlyCheckbutton.Name = "readonlyCheckbutton";
			this.readonlyCheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Read only mode");
			this.readonlyCheckbutton.DrawIndicator = true;
			this.readonlyCheckbutton.UseUnderline = true;
			this.GtkAlignment3.Add (this.readonlyCheckbutton);
			this.frame1.Add (this.GtkAlignment3);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Edit properties</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			w1.Add (this.frame1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.frame1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Internal child SecretariaElectrial.Preferences.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.CanDefault = true;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseStock = true;
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = "gtk-close";
			w8.Add (this.buttonClose);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonClose]));
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 299;
			this.DefaultHeight = 149;
			this.Show ();
			this.pathFileChooserButton.SelectionChanged += new global::System.EventHandler (this.OnPathFileChooserButtonSelectionChanged);
			this.readonlyCheckbutton.Toggled += new global::System.EventHandler (this.OnReadonlyCheckbuttonToggled);
			this.buttonClose.Clicked += new global::System.EventHandler (this.OnButtonCloseClicked);
		}
	}
}
